all: 
	chmod +x JackAnalyzer

project10.tar: README Makefile JackAnalyzer.py CompilationEngine.py JackTokenizer.py JackAnalyzer
	tar -cvf project10.tar README Makefile JackAnalyzer.py CompilationEngine.py JackTokenizer.py JackAnalyzer
